name: build and push docker image

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "23 13 3 * *"
  workflow_dispatch:

jobs:  
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: python:3-slim
          image: serotonie/aurorapy2mqtt # update for your image
    
      - name: Checkout
        uses: actions/checkout@v4
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: serotonie/aurorapy2mqtt:latest
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
