name: build and push docker image

on:
  schedule:
    - cron: "23 13 * * *"
  workflow_dispatch:

jobs:  
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: python:3-slim
          image: serotonie/aurorapy2mqtt:latest # update for your image
    
      - name: Checkout
        uses: actions/checkout@v4
        if: steps.baseupdatecheck.outputs.needs-updating == 'true' || github.event_name == 'workflow_dispatch'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.baseupdatecheck.outputs.needs-updating == 'true' || github.event_name == 'workflow_dispatch'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.baseupdatecheck.outputs.needs-updating == 'true' || github.event_name == 'workflow_dispatch'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true' || github.event_name == 'workflow_dispatch'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}        
        if: steps.baseupdatecheck.outputs.needs-updating == 'true' || github.event_name == 'workflow_dispatch'
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/serotonie/aurorapy2mqtt:latest
            serotonie/aurorapy2mqtt:latest
        if: steps.baseupdatecheck.outputs.needs-updating == 'true' || github.event_name == 'workflow_dispatch'
